#!/usr/bin/env bash

source "$(dirname "${BASH_SOURCE[0]}")"/helpers

# helpers enables tracing, which would leak the password into the job log
set +x

OBS_PASSWORD=${OBS_PASSWORD:-}
if [[ -z "$OBS_PASSWORD" ]]; then
    echo "OBS_PASSWORD is not set" >&2
    exit 1
fi

install_osc

umask 077
printf "[general]\napiurl = https://api.opensuse.org\n[https://api.opensuse.org]\nuser=cri-o-release-bot\npass=%s\n" "$OBS_PASSWORD" >~/.oscrc
